### ISSUE TITLE
Add geoip2 to conda or conda-forge

### ISSUE THREAD

**Issue by doaa-altarawy** [maxmind/GeoIP2-python#74]
It will be very helpful to be able to install geoip2 through the standard conda or conda-forge, just like the legacy geoip. Currently, geoip2 is only available through activisiongamescience channel, but conda-forge is a much more popular one.

**Comment by oschwald** [comment]
We don't maintain a Conda package for GeoIP Legacy. Is there a particular reason why you prefer to install through Conda rather than with `pip`?

**Comment by doaa-altarawy** [comment]
I meant like this 
https://anaconda.org/conda-forge/geoip

We use geoip2 in the automated build of  our scientific applications and it would be nice to build the whole environment from the same conda file. Conda is very popular in scientific domains.

**Comment by oschwald** [comment]
It looks like that package is for `libGeoIP` rather than the Python GeoIP module. Are you looking for the equivalent for `libmaxminddb`? If so, this would be more appropriately opened against the library.

We don't maintain the `libGeoIP` package. I am not sure who does, but maybe they would be willing to make a similar package for `libmaxminddb`.

**Comment by oschwald** [comment]
There appears to be a [conda-forge package](https://anaconda.org/conda-forge/geoip2) now. I am going to go ahead and close. this.
